### ISSUE TITLE
'from augment import Augmenter' Problem and GPU Restrictions

### ISSUE THREAD

**Issue by mflp** [ZJU-DAILY/CampER#1]
1. I have a compilation problem while trying to run your CampER code.  

Although I installed the augment library (or augment tool) with 'pip install augment', I do take the following error: 

"Traceback (most recent call last):
  File "~/CAMPER/Code/CampER-main/main.py", line 9, in <module>
    from data import *
  File "~/CAMPER/Code/CampER-main/data.py", line 8, in <module>
    from augment import Augmenter
ImportError: cannot import name 'Augmenter' from 'augment' (~/CAMPER/Code/CampER-main/.../lib/python3.9/site-packages/augment.py)"

**Do I install, by any chance, a wrong library? Could you enlighten it?**

2. I have a quick question on GPU memory capacity. 

Now, I haven't been able to pass over the compilation process. But, in case that I passed it, I would need to have a simple answer to the following GPU capacity question:
 
**'NVIDIA A100 40G GPU' is listed as a requirement. _If I have 32 GB GPU working, then, with longer running times, is there any chance to run the code on 32GB GPU or 40GB GPU memory is a must?_**   

Thanks for your time.

**Comment by yuxiang-guo** [comment]
Thanks for your questions. 
The error about importing 'Augmenter' is due to the code version. The 'Augmenter' is not used in this version, so you can just delete line 8 in data.py 'from augment import Augmenter'. Thanks for your reminder. I have updated data.py.

As for the GPU capacity, you can try to decrease the batch size, but the performance may be affected.
